### PR TITLE
add an automated version created via a script

### PR DESCRIPTION
**Pull request by rtward**
Thought I might take a swing at writing a script to do this.  Currently it finds the links, removes the facebook, pateron, and merch ones, then take the last five.  I can refine a bit more if anyone has a suggestion.

### CODE REVIEW

**Comment by gcluley** [comment]
Wow. How cool is this. It definitely reduces some of the work. The first episode which included a "Pick of the week" was episode 23 I think, so any episodes earlier than that can be ignored.

**Comment by rtward** [comment]
Okay, early episodes are removed and I fixed the em-dash formatting on the description text output.  Should be mostly copy and paste now.

**Comment by jonbeton** [comment]
I like this. Because I want to avoid wasting other people's time (people that will manually add entries now) I immediately went ahead with this pull request.
There were six merge conflicts. I selected to keep the one's on master because this script always selects five items and I assume the content on master is more accurate because they typically have three items as expected.

**Comment by nathan-embedism** [comment]
Just seen this! What’s the plan now, would you still like us to do stuff?

**Comment by jonbeton** [comment]
Hi Nathan, the master README.md now contains a rough draft of the pick-of-the-week info. Sometimes there's too many links, sometimes one's missing.
There is no official way forward yet, but this is the current plan:
- Verify and update the links in README.md for each episode.
- Add the numbers of the verified episodes in validated.txt.
Simply have a look at my recent commits - should be straightforward.
You can push directly into master, no need for pull requests.

**Pull request merged**
